spring.application.name=travel-agency-final-project
spring.profiles.active=test
spring.messages.encoding=UTF-8
app.upload.dir=file:D:/travel-agency-uploads/


logging.level.org.springframework.security=DEBUG
jwt.secret=super_secret_key_for_warehouse_system_1234567890_security

spring.jpa.properties.hibernate.globally_quoted_identifiers=false