spring.datasource.url=jdbc:h2:tcp://localhost:9092/D:/data/travel_agency
#spring.datasource.url=jdbc:h2:file:D:/data/travel_agency;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
